name: appdiphuot
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  buttons_tabbar: ^1.3.6
  get: ^4.6.5
  flutter_svg: ^2.0.6
  url_launcher: ^6.1.11
  shared_preferences: ^2.1.1
  avatar_glow: ^2.0.2
  circular_bottom_navigation: ^2.3.0
  multi_image_picker_view: ^0.0.15
  image_picker: ^0.8.7+5
  google_maps_place_picker_mb: ^3.0.2
  google_maps_flutter: ^2.2.8
  google_maps_flutter_android: ^2.4.15
  omni_datetime_picker: ^1.0.7
  date_format: ^2.0.7
  lite_rolling_switch: ^1.0.1
  forked_slider_button: ^2.0.2
  lottie: ^2.4.0
  slide_countdown: ^0.6.0
  overlay_loading_progress: ^1.0.1
  focus_detector_v2: ^3.1.0+1
  google_maps_directions: ^0.0.3+4
  flutter_polyline_points: ^1.0.0
  flutter_native_splash: ^2.3.0
  flutter_image_slideshow: ^0.1.5
  flutter_rating_bar: ^4.0.1
  modal_bottom_sheet: 3.0.0-pre
  overlay_support: ^2.1.0

  google_sign_in: ^6.1.3
  json_annotation: ^4.8.1
  logger: ^1.3.0
  event_bus: ^2.0.0
  rate: ^0.0.2

  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  firebase_messaging: ^14.6.2
  cloud_functions: ^4.3.2
#  firebase_database: ^10.2.2
  flutter_fcm: ^1.0.12
  flutter_fcm_wrapper: ^0.0.2

# chat
  flutter_chat_types: ^3.6.1
  flutter_firebase_chat_core: ^1.6.7
  flutter_chat_ui: ^1.6.8
  uuid: ^3.0.7

  cached_memory_image: ^1.3.1
  marquee: ^2.2.3
#  http: ^1.0.0
  dio: ^5.2.0+1
  comment_tree: ^0.3.0
  dropdown_button2: ^2.1.4

  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

# use this page to gen data class https://javiercbk.github.io/json_to_dart/
#  json_serializable: ^6.7.0
#  build_runner: ^2.4.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/ic_launcher.png"
    background_color: "#FF42A5F5"
    theme_color: "#FF42A5F5"
    windows:
      generate: true
      image_path: "assets/images/ic_launcher.png"
      icon_size: 48 # min:48, max:256, default: 48
    macos:
      generate: true
      image_path: "assets/images/ic_launcher.png"
#  flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/files/
    - assets/images/
