name: appdiphuot
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
#  syncfusion_flutter_charts: ^21.2.6
  cupertino_icons: ^1.0.5
#  percent_indicator: ^4.2.3
#  firebase_auth: ^4.6.1
#  cloud_firestore: ^4.7.1
#  firebase_core: ^2.13.0
#  get_cli: ^1.8.4
  buttons_tabbar: ^1.3.6
#  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
#  fl_chart: ^0.62.0
#  google_maps_flutter: ^2.2.8
#  google_fonts:
#  geolocator: ^9.0.2
#  permission_handler: ^10.2.0
#  location: ^4.4.0
  flutter_svg: ^2.0.6
#  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.1.11
#  open_street_map_search_and_pick: ^0.0.17
  shared_preferences: ^2.1.1
  avatar_glow: ^2.0.2
  circular_bottom_navigation: ^2.3.0
  multi_image_picker_view: ^0.0.15
#  map_location_picker: ^1.2.0
#  location_picker_flutter_map: ^1.2.0
  google_maps_place_picker_mb: ^3.0.2
  google_maps_flutter: ^2.2.8
  google_maps_flutter_android: ^2.4.15
  omni_datetime_picker: ^1.0.7
  date_format: ^2.0.7
  lite_rolling_switch: ^1.0.1
  forked_slider_button: ^2.0.2
  lottie: ^2.3.2
  slide_countdown: ^0.6.0
#  flutter_easyloading: ^3.0.5
  overlay_loading_progress: ^1.0.1
  focus_detector_v2: ^3.1.0+1
#  google_directions_api_nic: ^0.9.1
  google_maps_directions: ^0.0.3+4
  flutter_polyline_points: ^1.0.0

  #https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.3.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  google_sign_in: ^6.1.3

  json_annotation: ^4.8.1

  #https://pub.dev/packages/logger
  logger: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

  json_serializable: ^6.7.0
  build_runner: ^2.4.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/ic_launcher.png"
    background_color: "#FF42A5F5"
    theme_color: "#FF42A5F5"
    windows:
      generate: true
      image_path: "assets/images/ic_launcher.png"
      icon_size: 48 # min:48, max:256, default: 48
    macos:
      generate: true
      image_path: "assets/images/ic_launcher.png"
#  flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/files/
    - assets/videos/
    - assets/images/
